name: brainsec
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.10.0
  - pip
  - libvips
  - openslide
  - pip:
    - pillow
    - pyvips
    - numpy
    - pandas
    - ipykernel
    - scikit-learn
    - scikit-image
    - matplotlib
    - torchvision
    - czifile
    - torch
    - opencv-python
    - tqdm
    - beautifulsoup4
    - argparse
    - psutil
    - xmltodict
    - openslide-python